language: python

cache: pip

python: 
    - "3.7"
    - "3.8"

install:
    - pip install -r requirements.txt

script:
    - python -m pytest -vvv --cov=./ tests/
    - black ./

after_success:
  - bash <(curl -s https://codecov.io/bash)
